FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Directory.Build.props", "."]
COPY ["Directory.Build.targets", "."]
COPY ["Directory.Packages.props", "."]
COPY ["global.json", "."]
COPY ["nuget.config", "."]

COPY ["src/", "src/"]

RUN dotnet restore "src/Identity.API/Identity.API.csproj"
RUN dotnet build "src/Identity.API/Identity.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "src/Identity.API/Identity.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
EXPOSE 8080
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Identity.API.dll"]
